{% set name = "jaro-winkler" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/richmilne/JaroWinkler/archive/refs/tags/pypi-v{{ version }}.tar.gz
  sha256: 90289409c9c7e909d9626ca61de8b46b318939b7e4d3e8c25ed94f4524991c0b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - jaro
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/richmilne/JaroWinkler
  summary: 'Original, standard and customisable versions of the Jaro-Winkler functions.'
  license: GPL-3.0-or-later
  license_family: GPL 
  license_file: LICENSE
  dev_url: https://github.com/richmilne/JaroWinkler

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
